package com.Wsdl2Code.WebServices.PublicPortalServiceJSON;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 6/9/2014 3:15:59 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class FeeTypeVO implements KvmSerializable {
    
    public String descript;
    public String feeCategoryName;
    public long id;
    public boolean idSpecified;
    public int schoolNumber;
    public boolean schoolNumberSpecified;
    public int sort;
    public boolean sortSpecified;
    public String title;
    
    public FeeTypeVO(){}
    
    public FeeTypeVO(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("descript"))
        {
            Object obj = soapObject.getProperty("descript");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                descript = j.toString();
            }else if (obj!= null && obj instanceof String){
                descript = (String) obj;
            }
        }
        if (soapObject.hasProperty("feeCategoryName"))
        {
            Object obj = soapObject.getProperty("feeCategoryName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feeCategoryName = j.toString();
            }else if (obj!= null && obj instanceof String){
                feeCategoryName = (String) obj;
            }
        }
        if (soapObject.hasProperty("id"))
        {
            Object obj = soapObject.getProperty("id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                id = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                id = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("idSpecified"))
        {
            Object obj = soapObject.getProperty("idSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                idSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                idSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("schoolNumber"))
        {
            Object obj = soapObject.getProperty("schoolNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                schoolNumber = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                schoolNumber = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("schoolNumberSpecified"))
        {
            Object obj = soapObject.getProperty("schoolNumberSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                schoolNumberSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                schoolNumberSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("sort"))
        {
            Object obj = soapObject.getProperty("sort");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                sort = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                sort = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("sortSpecified"))
        {
            Object obj = soapObject.getProperty("sortSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                sortSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("title"))
        {
            Object obj = soapObject.getProperty("title");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                title = j.toString();
            }else if (obj!= null && obj instanceof String){
                title = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return descript;
            case 1:
                return feeCategoryName;
            case 2:
                return id;
            case 3:
                return idSpecified;
            case 4:
                return schoolNumber;
            case 5:
                return schoolNumberSpecified;
            case 6:
                return sort;
            case 7:
                return sortSpecified;
            case 8:
                return title;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "descript";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "feeCategoryName";
                break;
            case 2:
                info.type = Long.class;
                info.name = "id";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "idSpecified";
                break;
            case 4:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "schoolNumber";
                break;
            case 5:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "schoolNumberSpecified";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "sort";
                break;
            case 7:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "sortSpecified";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "title";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
